const API_URL=window.EXPERIMENT_CONFIG?.apiUrl||"";
const addressData=window.THAI_ADDRESS_DATA||[],form=document.querySelector("#orderForm"),rawOrder=document.querySelector("#rawOrder"),itemsList=document.querySelector("#itemsList"),itemTemplate=document.querySelector("#itemTemplate"),itemCount=document.querySelector("#itemCount"),formMessage=document.querySelector("#formMessage"),shopNameInput=document.querySelector("#shopName"),shopSuggestions=document.querySelector("#shopSuggestions"),provinceInput=document.querySelector("#province"),districtInput=document.querySelector("#district"),subdistrictInput=document.querySelector("#subdistrict"),summaryContent=document.querySelector("#summaryContent");
const provincePicker=document.querySelector("#provincePicker"),districtPicker=document.querySelector("#districtPicker"),subdistrictPicker=document.querySelector("#subdistrictPicker"),addressSheet=document.querySelector("#addressSheet"),pickerTitle=document.querySelector("#pickerTitle"),pickerSearch=document.querySelector("#pickerSearch"),pickerOptions=document.querySelector("#pickerOptions");
const normalize=(value="")=>value.trim().replace(/\s+/g,""),fillList=(select,values,label)=>{select.innerHTML="";select.append(new Option(label,""));values.forEach(value=>select.append(new Option(value,value)))},getProvince=()=>addressData.find(item=>normalize(item.name_th)===normalize(provinceInput.value)),getDistrict=(province=getProvince())=>province?.districts?.find(item=>normalize(item.name_th)===normalize(districtInput.value)),getSubdistrict=(district=getDistrict())=>district?.sub_districts?.find(item=>normalize(item.name_th)===normalize(subdistrictInput.value));
function addHint(input,text){const hint=document.createElement("small");hint.className="field-hint";hint.textContent=text;input.after(hint);return hint}const hints={province:addHint(provinceInput,"มีข้อมูลครบทุกจังหวัด"),district:addHint(districtInput,""),subdistrict:addHint(subdistrictInput,"")};
function setHint(el,text,warning=false){el.textContent=text;el.classList.toggle("warning",warning)}
function setPicker(button,value,fallback,disabled=false){button.firstChild.textContent=`${value||fallback} `;button.disabled=disabled}
function refreshAddress(level){if(level==="province"){districtInput.value="";subdistrictInput.value=""}if(level==="district")subdistrictInput.value="";const selectedDistrict=districtInput.value,selectedSubdistrict=subdistrictInput.value,province=getProvince();setPicker(provincePicker,provinceInput.value,"เลือกจังหวัด");if(province){fillList(districtInput,province.districts.map(x=>x.name_th),"เลือกอำเภอ");districtInput.value=selectedDistrict;districtInput.disabled=false;setHint(hints.province,`เลือกได้ ${province.districts.length} อำเภอ`)}else{fillList(districtInput,[],"เลือกจังหวัดก่อน");fillList(subdistrictInput,[],"เลือกอำเภอก่อน");districtInput.disabled=true;subdistrictInput.disabled=true;setHint(hints.province,"มีข้อมูลครบทุกจังหวัด",false)}const district=getDistrict(province);setPicker(districtPicker,districtInput.value,province?"เลือกอำเภอ":"เลือกจังหวัดก่อน",!province);if(district){fillList(subdistrictInput,district.sub_districts.map(x=>x.name_th),"เลือกตำบล");subdistrictInput.value=selectedSubdistrict;subdistrictInput.disabled=false;setHint(hints.district,`เลือกได้ ${district.sub_districts.length} ตำบล`)}else{fillList(subdistrictInput,[],"เลือกอำเภอก่อน");subdistrictInput.disabled=true;setHint(hints.district,"",false)}const subdistrict=getSubdistrict(district);setPicker(subdistrictPicker,subdistrictInput.value,district?"เลือกตำบล":"เลือกอำเภอก่อน",!district);setHint(hints.subdistrict,subdistrict?.zip_code?`รหัสไปรษณีย์ ${subdistrict.zip_code}`:"",false);updateSummary()}
let activePicker=null,activeValues=[];
function renderPickerOptions(query=""){const term=normalize(query);pickerOptions.innerHTML="";activeValues.filter(value=>!term||normalize(value).includes(term)).forEach(value=>{const button=document.createElement("button");button.type="button";button.textContent=value;button.addEventListener("click",()=>{activePicker.input.value=value;refreshAddress(activePicker.level);closeAddressPicker()});pickerOptions.append(button)})}
function openAddressPicker(input,level,title){if(input.disabled)return;activePicker={input,level};activeValues=[...input.options].map(option=>option.value).filter(Boolean);pickerTitle.textContent=title;pickerSearch.value="";renderPickerOptions();addressSheet.hidden=false;document.body.classList.add("picker-open");setTimeout(()=>pickerSearch.focus(),50)}
function closeAddressPicker(){addressSheet.hidden=true;document.body.classList.remove("picker-open");activePicker=null}
function productFromLine(line){if(/ถ้วย/.test(line))return"น้ำถ้วย";if(/1[,.]?500|1500/.test(line))return"น้ำ 1,500 มล.";if(/350/.test(line))return"น้ำ 350 มล.";if(/600/.test(line))return"น้ำ 600 มล.";return"อื่นๆ"}
function parseLine(line){if(!/น้ำ|350|600|1500|1,500|ถ้วย/.test(line))return null;const clean=line.replace(/,/g,""),size=clean.match(/(?:350|600|1500|ถ้วย)/),after=size?clean.slice(size.index+size[0].length):clean,quantity=after.match(/(?:=|จำนวน\s*)?\s*(\d{1,6})\s*(?:แพ[็คก]*|ลัง|เลท)?/i)?.[1]||"",free=clean.match(/แถม(?:ฟรี)?\s*(?:น้ำ\s*(?:350|600|1500)?\s*)?(\d{1,6})/)?.[1]||"",price=clean.match(/\(((?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2}))\s*-?\)|ราคา\s*((?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2}))|(?:^|\s)((?:\d{1,4}(?:\.\d{1,2})?|\.\d{1,2}))\s*\/\s*แถม/)?.slice(1).find(Boolean)||"",unit=/ลัง/.test(line)?"ลัง":/เลท/.test(line)?"เลท":"แพ็ค";return{product:productFromLine(line),quantity,unit,free,price:price.startsWith(".")?`0${price}`:price}}
function addItem(data={}){document.querySelector("#emptyItems")?.remove();const item=itemTemplate.content.firstElementChild.cloneNode(true);item.querySelector(".item-product").value=data.product||"น้ำ 600 มล.";item.querySelector(".item-quantity").value=data.quantity||"";item.querySelector(".item-unit").value=data.unit||"แพ็ค";item.querySelector(".item-free").value=data.free||"";item.querySelector(".item-price").value=data.price||"";item.querySelector(".remove-button").addEventListener("click",()=>{item.remove();renumberItems();updateSummary()});item.querySelectorAll("input,select").forEach(control=>control.addEventListener("input",updateSummary));itemsList.append(item);renumberItems();updateSummary()}
function renumberItems(){const items=[...itemsList.querySelectorAll(".order-item")];items.forEach((item,index)=>item.querySelector(".item-number").textContent=`รายการ ${index+1}`);itemCount.textContent=items.length?`${items.length} รายการ`:"ยังไม่มีรายการ";if(!items.length&&!document.querySelector("#emptyItems"))itemsList.innerHTML='<div class="empty-state" id="emptyItems">กดเพิ่มรายการ แล้วกรอกชื่อสินค้าและหน่วยขาย</div>'}
function extractDetails(lines){const shop=document.querySelector("#shopName"),date=document.querySelector("#deliveryDate"),note=document.querySelector("#note"),first=lines.find(line=>!/น้ำ|350|600|1500|ถ้วย|ส่ง|แถม/.test(line));if(!shop.value&&first)shop.value=first;const foundDate=rawOrder.value.match(/ส่ง\s*(วันนี้|พรุ่งนี้|วัน(?:จันทร์|อังคาร|พุธ|พฤหัส(?:บดี)?|ศุกร์|เสาร์|อาทิตย์)(?:ที่)?\s*\d{0,2}(?:\/\d{1,2}\/\d{2,4})?)/)?.[1];if(!date.value&&foundDate)date.value=foundDate;const deliveryNote=lines.filter(line=>/โกดัง|ลงร้าน|ติดต่อ|ราคา/.test(line)).join(" / ");if(!note.value&&deliveryNote)note.value=deliveryNote}
function parseOrder(){const lines=rawOrder.value.split(/\n|(?=น้ำ\s*(?:350|600|1500|ถ้วย))/).map(line=>line.trim()).filter(Boolean),parsed=lines.map(parseLine).filter(item=>item?.quantity);itemsList.innerHTML="";parsed.forEach(addItem);extractDetails(lines);formMessage.className="form-message";if(!parsed.length){renumberItems();formMessage.textContent="ยังแยกรายการไม่ได้ ลองขึ้นบรรทัดใหม่ให้สินค้าแต่ละรายการ หรือกดเพิ่มรายการเอง"}else{formMessage.textContent=`แยกได้ ${parsed.length} รายการ กรุณาตรวจจำนวนและของแถมอีกครั้ง`;formMessage.classList.add("success");document.querySelector("#items-title").scrollIntoView({behavior:"smooth",block:"start"})}updateSummary()}
function getItems(){return[...itemsList.querySelectorAll(".order-item")].map(item=>({product:item.querySelector(".item-product").value,quantity:item.querySelector(".item-quantity").value,unit:item.querySelector(".item-unit").value,free:item.querySelector(".item-free").value,price:item.querySelector(".item-price").value}))}function esc(value){const div=document.createElement("div");div.textContent=value||"-";return div.innerHTML}
function updateSummary(){const values=Object.fromEntries(new FormData(form)),items=getItems();if(!values.shopName&&!values.salesName&&!items.length){summaryContent.innerHTML='<p class="summary-placeholder">ข้อมูลที่กรอกจะแสดงตรงนี้</p>';return}const area=[values.subdistrict&&`ต.${values.subdistrict}`,values.district&&`อ.${values.district}`,values.province&&`จ.${values.province}`].filter(Boolean).join(" "),itemHtml=items.map(item=>`<div class="summary-item"><span>${esc(item.product)} × ${esc(item.quantity)} ${esc(item.unit)}${item.free?` + แถม ${esc(item.free)}`:""}</span>${item.price?`<strong>${esc(item.price)} บาท</strong>`:""}</div>`).join("");summaryContent.innerHTML=`<div class="summary-group"><span class="summary-label">ร้านค้า</span><div class="summary-value">${esc(values.shopName)}</div></div>${itemHtml?`<div class="summary-group"><span class="summary-label">สินค้า</span>${itemHtml}</div>`:""}<div class="summary-group"><span class="summary-label">พื้นที่ส่ง</span><div class="summary-value">${esc(area||"-")}${values.address?`\n${esc(values.address)}`:""}</div></div><div class="summary-group"><span class="summary-label">กำหนดส่ง / หมายเหตุ</span><div class="summary-value">${esc(values.deliveryDate||"ไม่ระบุ")}${values.note?` · ${esc(values.note)}`:""}</div></div><div class="summary-group"><span class="summary-label">ผู้กรอก</span><div class="summary-value">${esc(values.salesName)}</div></div>`}
const SHOP_STORAGE_KEY="mulriver-shops-v1";
let rememberedShops=[],activeShopIndex=-1;
function shopKey(shop){return[shop.name,shop.province,shop.district,shop.subdistrict].map(value=>normalize(String(value||"").replace(/^ร้าน/,""))).join("|")}
function mergeShops(shops=[]){const map=new Map(rememberedShops.map(shop=>[shopKey(shop),shop]));shops.forEach(shop=>{if(shop?.name&&shop?.province&&shop?.district&&shop?.subdistrict)map.set(shopKey(shop),shop)});rememberedShops=[...map.values()];try{localStorage.setItem(SHOP_STORAGE_KEY,JSON.stringify(rememberedShops.slice(0,500)))}catch(error){}renderShopSuggestions()}
function loadLocalShops(){try{mergeShops(JSON.parse(localStorage.getItem(SHOP_STORAGE_KEY)||"[]"))}catch(error){rememberedShops=[]}}
window.receiveSavedShops=function(data){mergeShops(Array.isArray(data)?data:[])};
window.rememberShop=function(shop){mergeShops([shop])};
function loadSharedShops(){const script=document.createElement("script");script.src=`${API_URL}?action=shops&callback=receiveSavedShops&_=${Date.now()}`;script.async=true;document.head.append(script)}
function shopScore(shop,term){const name=normalize(shop.name).toLowerCase(),needle=normalize(term).toLowerCase();if(!needle)return 0;if(name===needle)return 100;if(name.startsWith(needle))return 80-name.length;if(name.includes(needle))return 60-name.indexOf(needle);let matched=0,cursor=0;for(const char of needle){const found=name.indexOf(char,cursor);if(found<0)return 0;matched++;cursor=found+1}return matched===needle.length?30-(name.length-needle.length):0}
function closeShopSuggestions(){shopSuggestions.hidden=true;shopNameInput.setAttribute("aria-expanded","false");activeShopIndex=-1}
function selectRememberedShop(shop){shopNameInput.value=shop.name;provinceInput.value=shop.province;refreshAddress("province");districtInput.value=shop.district;refreshAddress("district");subdistrictInput.value=shop.subdistrict;refreshAddress();closeShopSuggestions();updateSummary()}
function renderShopSuggestions(){const term=shopNameInput.value.trim();if(!term){closeShopSuggestions();return}const matches=rememberedShops.map(shop=>({shop,score:shopScore(shop,term)})).filter(item=>item.score>0).sort((a,b)=>b.score-a.score||a.shop.name.localeCompare(b.shop.name,"th")).slice(0,6);shopSuggestions.innerHTML="";matches.forEach(({shop},index)=>{const button=document.createElement("button");button.type="button";button.className="shop-option";button.setAttribute("role","option");button.innerHTML=`<strong>${esc(shop.name)}</strong><small>ต.${esc(shop.subdistrict)} · อ.${esc(shop.district)} · จ.${esc(shop.province)}</small>`;button.addEventListener("pointerdown",event=>event.preventDefault());button.addEventListener("click",()=>selectRememberedShop(shop));shopSuggestions.append(button)});shopSuggestions.hidden=!matches.length;shopNameInput.setAttribute("aria-expanded",String(Boolean(matches.length)));activeShopIndex=-1}
shopNameInput.addEventListener("input",renderShopSuggestions);
shopNameInput.addEventListener("focus",renderShopSuggestions);
shopNameInput.addEventListener("blur",()=>setTimeout(closeShopSuggestions,120));
shopNameInput.addEventListener("keydown",event=>{const options=[...shopSuggestions.querySelectorAll(".shop-option")];if(shopSuggestions.hidden||!options.length)return;if(event.key==="ArrowDown"||event.key==="ArrowUp"){event.preventDefault();activeShopIndex=(activeShopIndex+(event.key==="ArrowDown"?1:-1)+options.length)%options.length;options.forEach((option,index)=>option.classList.toggle("active",index===activeShopIndex))}else if(event.key==="Enter"&&activeShopIndex>=0){event.preventDefault();options[activeShopIndex].click()}else if(event.key==="Escape")closeShopSuggestions()});
document.addEventListener("click",event=>{if(!event.target.closest(".shop-field"))closeShopSuggestions()});
loadLocalShops();
loadSharedShops();
fillList(provinceInput,addressData.map(item=>item.name_th),"เลือกจังหวัด");
provincePicker.addEventListener("click",()=>openAddressPicker(provinceInput,"province","เลือกจังหวัด"));
districtPicker.addEventListener("click",()=>openAddressPicker(districtInput,"district","เลือกอำเภอ"));
subdistrictPicker.addEventListener("click",()=>openAddressPicker(subdistrictInput,"subdistrict","เลือกตำบล"));
pickerSearch.addEventListener("input",()=>renderPickerOptions(pickerSearch.value));
document.querySelector("#closePicker").addEventListener("click",closeAddressPicker);
document.querySelector(".picker-backdrop").addEventListener("click",closeAddressPicker);
provinceInput.addEventListener("change",()=>refreshAddress("province"));
provinceInput.addEventListener("input",()=>refreshAddress("province"));
districtInput.addEventListener("change",()=>refreshAddress("district"));
districtInput.addEventListener("input",()=>refreshAddress("district"));
subdistrictInput.addEventListener("change",()=>refreshAddress("subdistrict"));
subdistrictInput.addEventListener("input",()=>refreshAddress("subdistrict"));
form.addEventListener("input",updateSummary);document.querySelector("#parseButton")?.addEventListener("click",parseOrder);document.querySelector("#addItemButton").addEventListener("click",()=>addItem());document.querySelector("#exampleButton")?.addEventListener("click",()=>{rawOrder.value="ร้านโชคเจริญ\nน้ำ 600 = 500 แพ็ค แถม 50\nน้ำ 1500 = 50 แพ็ค (25-)\nส่งวันจันทร์ หน้าโกดัง";updateSummary();rawOrder.focus()});document.querySelector("#resetButton").addEventListener("click",()=>{if(!confirm("ล้างข้อมูลออเดอร์ทั้งหมดใช่ไหม?"))return;form.reset();itemsList.innerHTML='<div class="empty-state" id="emptyItems">กดเพิ่มรายการ แล้วกรอกชื่อสินค้าและหน่วยขาย</div>';refreshAddress();renumberItems();formMessage.textContent="";formMessage.className="form-message";updateSummary()});form.addEventListener("submit",event=>{event.preventDefault();formMessage.className="form-message";if(!getItems().length){formMessage.textContent="กรุณาเพิ่มรายการสินค้าอย่างน้อย 1 รายการ";return}if(!form.reportValidity())return;if(!getProvince()||!getDistrict()||!getSubdistrict()){formMessage.textContent="กรุณาเลือกจังหวัด อำเภอ และตำบลจากรายการให้ถูกต้อง";return}formMessage.textContent="บันทึกออเดอร์ตัวอย่างเรียบร้อย พร้อมเชื่อมต่อส่งเข้าระบบจริง";formMessage.classList.add("success");formMessage.scrollIntoView({behavior:"smooth",block:"center"})});
